import type { Phase, Ticket, Year } from "./data/types";

export interface PortfolioArtifact {
  title: string;
  content: string;
  filename: string;
}

export function generatePhasePortfolio(
  year: Year,
  phase: Phase,
  score?: number,
  evidenceNotes?: string,
): PortfolioArtifact {
  const filename = `${phase.id}-${phase.title.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase()}.md`;
  const content = `# ${phase.id} — ${phase.title}

## Year ${year.number}: ${year.title}

## Business Scenario
This lab is part of the IAM Career Lab, a four-year progressive training platform. In Year ${year.number}, the learner develops ${year.roleTarget} skills.

## Problem / Goal
${phase.goal}

## Objectives
${phase.objectives.map((o) => `- ${o}`).join("\n")}

## Student Outcomes
${phase.studentOutcome.map((o) => `- ${o}`).join("\n")}

## Topics Covered
${phase.topics.map((t) => `- ${t}`).join("\n")}

## Evidence Collected
${phase.evidence.map((e) => `- ${e}`).join("\n")}

## Acceptance Criteria
${phase.acceptance.map((a) => `- ${a}`).join("\n")}

## Assessment
${score ? `Instructor Score: ${score}%` : "Assessment pending — complete the lab and request evaluation from the Ollama tutor."}

${evidenceNotes ? `## Evidence Notes\n${evidenceNotes}\n` : ""}

## Implementation Notes
<!-- Document the steps you took to complete this lab -->

## Troubleshooting
<!-- Document any issues encountered and how you resolved them -->

## Root Cause Analysis
<!-- If applicable, document the root cause you identified -->

## Remediation
<!-- Document the fix or remediation applied -->

## Validation
<!-- Document how you validated the solution -->

## Security Considerations
- Applied least privilege throughout the exercise
- Used only authorized lab systems and synthetic data
- No real credentials or secrets were stored or committed

## Lessons Learned
<!-- Document what you learned from this lab -->

## Skills Demonstrated
${phase.topics.map((t) => `- ${t}`).join("\n")}

## What Would Change in Production
<!-- Document how this would differ in a real enterprise environment -->

---
*Generated by the IAM Career Lab platform*
*Label: Hands-on lab project — not production experience*
`;

  return { title: `${phase.id} — ${phase.title}`, content, filename };
}

export function generateTicketPortfolio(ticket: Ticket, year: Year): PortfolioArtifact {
  const filename = `${ticket.id}-${ticket.title.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase()}.md`;
  const content = `# ${ticket.id} — ${ticket.title}

## Incident Report

**Year:** ${year.number} — ${year.title}
**Priority:** ${ticket.priority}
**Affected Asset:** ${ticket.affectedAsset}

## Scenario
${ticket.scenario}

## Business Impact
${ticket.businessImpact}

## Symptoms
${ticket.symptoms.map((s) => `- ${s}`).join("\n")}

## Evidence Available
${ticket.evidenceAvailable.map((e) => `- ${e}`).join("\n")}

## Investigation
<!-- Document your investigation steps -->

## Root Cause Analysis
<!-- Document the root cause you identified (revealed after investigation) -->

## Remediation
${ticket.remediation}

## Acceptance Criteria
${ticket.acceptanceCriteria.map((a) => `- ${a}`).join("\n")}

## Validation
<!-- Document how you validated the fix -->

## Security Considerations
- Applied least privilege
- Used only authorized lab systems
- Preserved evidence per incident procedure
- No secrets stored or committed

## Lessons Learned
<!-- Document what you learned -->

## Escalation Threshold
${ticket.escalationThreshold}

---
*Generated by the IAM Career Lab platform*
*Label: Hands-on lab project — not production experience*
`;

  return { title: `${ticket.id} — ${ticket.title}`, content, filename };
}

export function generateYearPortfolio(year: Year): PortfolioArtifact {
  const filename = `year-${year.number}-portfolio-summary.md`;
  const content = `# Year ${year.number} Portfolio Summary — ${year.title}

## Role Target
${year.roleTarget}

## Main Outcome
${year.mainOutcome}

## Description
${year.description}

## Phases Completed
${year.phases.map((p) => `- [${p.id}] ${p.title} — ${p.goal}`).join("\n")}

## Career Gate
**${year.gate.title}**

Competencies demonstrated:
${year.gate.competencies.map((c) => `- ${c}`).join("\n")}

## Architecture
This lab is part of the IAM Career Lab enterprise:
- **Company:** IAM Career Lab
- **Domain:** lab.local
- **Network:** 10.10.10.0/24 (isolated Hyper-V private network)
- **DC01:** Windows Server with AD DS + DNS (10.10.10.10)
- **HD01:** Windows 11 client, domain-joined

## Skills Demonstrated
${year.phases.flatMap((p) => p.topics).map((t) => `- ${t}`).join("\n")}

## Employer-Facing Summary
"Completed a hands-on ${year.roleTarget} lab implementing ${year.phases.length} progressive phases covering ${year.phases.flatMap((p) => p.topics).length} key topics in a domain-based Windows enterprise environment."

*Label: Hands-on lab project — not production experience*

---
*Generated by the IAM Career Lab platform*
`;

  return { title: `Year ${year.number} Portfolio Summary`, content, filename };
}
