import type { Phase, Ticket, Year } from "./data/types";
import { architecture } from "./data/architecture";

export interface PortfolioArtifact {
  title: string;
  content: string;
  filename: string;
}

/** Shared footer. Centralised so the honesty label cannot drift between artifact types. */
const FOOTER = `---
*Generated by the IAM Career Lab platform.*
*Label: hands-on lab project in a simulated enterprise, not production work experience.*
*All organisations, identities and data in this artifact are fictional.*
`;

function slug(text: string): string {
  return text.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-|-$/g, "").toLowerCase();
}

/**
 * Renders the assessment line.
 *
 * Written as an explicit null check rather than a truthiness check: a score of
 * 0 is a real score and must not be reported as "assessment pending".
 */
function assessmentLine(score?: number): string {
  if (score === undefined || score === null || Number.isNaN(score)) {
    return "Assessment pending. Complete the lab and request evaluation from the tutor.";
  }
  return `Instructor score: ${score}% (passing threshold 80%)`;
}

export function generatePhasePortfolio(
  year: Year,
  phase: Phase,
  score?: number,
  evidenceNotes?: string,
): PortfolioArtifact {
  const filename = `${phase.id}-${slug(phase.title)}.md`;
  const content = `# ${phase.id} - ${phase.title}

**Year ${year.number}: ${year.title}** | Target role: ${year.roleTarget}

## Business scenario

This lab is set inside ${architecture.company}, a simulated enterprise running the
\`${architecture.domain}\` domain on an isolated ${architecture.networkPlan.subnet} network.
In Year ${year.number} the learner operates as ${year.roleTarget}.

## Problem / goal

${phase.goal}

## Objectives

${phase.objectives.map((o) => `- ${o}`).join("\n")}

## Topics covered

${phase.topics.map((t) => `- ${t}`).join("\n")}

## Evidence requirements

${phase.evidence.map((e) => `- ${e}`).join("\n")}

## Acceptance criteria

${phase.acceptance.map((a) => `- ${a}`).join("\n")}

## Assessment

${assessmentLine(score)}

${evidenceNotes && evidenceNotes.trim() ? `## Evidence notes\n\n${evidenceNotes.trim()}\n` : ""}
## Implementation notes

<!-- What you actually did, step by step, with the commands used -->

## Troubleshooting

<!-- What went wrong and how you narrowed it down -->

## Root cause analysis

<!-- The underlying cause, distinguished from the symptom -->

## Remediation

<!-- The fix applied, and why you chose it over the alternatives -->

## Validation

<!-- How you proved the fix worked, not just that the error stopped -->

## Security considerations

- Least privilege applied throughout
- Only authorised lab systems and synthetic data used
- No real credentials or secrets stored or committed

## Lessons learned

<!-- What you would do differently, and what you now check first -->

## Skills demonstrated

${phase.topics.map((t) => `- ${t}`).join("\n")}

## What would differ in production

<!-- Scale, blast radius, change control, and what this lab could not simulate -->

${FOOTER}`;

  return { title: `${phase.id} - ${phase.title}`, content, filename };
}

export interface TicketArtifactInput {
  diagnosis?: string;
  resolutionNotes?: string;
  hintsRevealed?: number;
  rootCauseRevealed?: boolean;
  status?: string;
}

/**
 * Renders an incident report.
 *
 * Note what is deliberately NOT written here: the supplied root cause and
 * remediation text. Emitting them would hand the learner a finished report
 * describing an investigation they did not perform, which is the opposite of
 * portfolio evidence. The learner's own diagnosis is included instead, along
 * with an honest record of how much assistance the ticket took.
 */
export function generateTicketPortfolio(
  ticket: Ticket,
  year: Year,
  input: TicketArtifactInput = {},
): PortfolioArtifact {
  const { diagnosis, resolutionNotes, hintsRevealed = 0, rootCauseRevealed = false, status } = input;

  const assistance = rootCauseRevealed
    ? `Root cause revealed after investigation. Hints used: ${hintsRevealed}.`
    : hintsRevealed > 0
      ? `Solved with ${hintsRevealed} hint${hintsRevealed === 1 ? "" : "s"} and without revealing the root cause.`
      : "Solved unaided, with no hints and without revealing the root cause.";

  const filename = `${ticket.id}-${slug(ticket.title)}.md`;
  const content = `# ${ticket.id} - ${ticket.title}

## Incident report

| Field | Value |
| --- | --- |
| Year | ${year.number} - ${year.title} |
| Priority | ${ticket.priority} |
| Affected asset | ${ticket.affectedAsset} |
| Status | ${status ?? "In progress"} |
| Environment | ${architecture.company} (\`${architecture.domain}\`), isolated lab |

## Scenario

${ticket.scenario}

## Business impact

${ticket.businessImpact}

## Symptoms observed

${ticket.symptoms.map((s) => `- ${s}`).join("\n")}

## Evidence available

${ticket.evidenceAvailable.map((e) => `- ${e}`).join("\n")}

## Investigation

${diagnosis && diagnosis.trim() ? diagnosis.trim() : "<!-- Your investigation steps and the evidence that led you to the cause -->"}

## Root cause analysis

<!-- State the underlying cause in your own words. Distinguish it clearly from the symptom. -->

## Remediation applied

<!-- What you changed, and why you chose that over the alternatives -->

## Validation

<!-- How you proved the issue was resolved rather than merely silent -->

## Reflection

${resolutionNotes && resolutionNotes.trim() ? resolutionNotes.trim() : "<!-- What you got right, what you missed, and what you would check first next time -->"}

## Acceptance criteria

${ticket.acceptanceCriteria.map((a) => `- ${a}`).join("\n")}

## Escalation threshold

${ticket.escalationThreshold}

## Security considerations

- Least privilege applied
- Only authorised lab systems used
- Evidence preserved per incident procedure
- No secrets, credentials or personal data stored or committed

## Assistance record

${assistance}

${FOOTER}`;

  return { title: `${ticket.id} - ${ticket.title}`, content, filename };
}

export function generateYearPortfolio(year: Year): PortfolioArtifact {
  const filename = `year-${year.number}-portfolio-summary.md`;
  const uniqueSkills = Array.from(new Set(year.phases.flatMap((p) => p.topics))).sort();

  const content = `# Year ${year.number} portfolio summary - ${year.title}

## Role target

${year.roleTarget}

## Main outcome

${year.mainOutcome}

## Scope

${year.description}

## Phases completed (${year.phases.length})

${year.phases.map((p) => `- **${p.id}** ${p.title} - ${p.goal}`).join("\n")}

## Career gate

**${year.gate.title}**

Competencies demonstrated:

${year.gate.competencies.map((c) => `- ${c}`).join("\n")}

## Lab environment

- **Company:** ${architecture.company} (fictional)
- **Domain:** ${architecture.domain}
- **Network:** ${architecture.networkPlan.subnet}, isolated private network
${architecture.networkPlan.assignments.map((a) => `- **${a.host}:** ${a.ip} - ${a.role}`).join("\n")}
- **Clients:** ${architecture.networkPlan.clients}

## Skills demonstrated (${uniqueSkills.length} distinct topics)

${uniqueSkills.map((t) => `- ${t}`).join("\n")}

## Summary for a CV or cover letter

Completed a structured, hands-on ${year.roleTarget} programme of ${year.phases.length} progressive
lab phases in a domain-based Windows enterprise environment, covering ${uniqueSkills.length}
distinct technical topics, with documented evidence, troubleshooting records and root-cause
analysis for each phase.

${FOOTER}`;

  return { title: `Year ${year.number} portfolio summary`, content, filename };
}
